### ISSUE TITLE
Add a registry for Aurelia Plugins

### ISSUE THREAD

**Issue by plwalters** [aurelia/registry#1]
The registry should contain basic information about each plugin.  To allow the registry to expand with additional properties, I propose we use an array of objects instead of a simple key:value pair.  Example - 

``` javascript
{
  "plugins": [
      {  
        "name": "i18next",
        "endpoint": "github",    // where to start looking?  github, npm, gist
        "location": "/zewa666/aurelia-i18next",   // where is it in the end point?
        "cli": true    // has a cli plugin to integrate?
      }
  ]
}
```

This will allow us to start by defining the required location information and possibly expand in the future to support other properties or special settings.

This would also allow us to start with using JSPM at the very least and potentially expand in to other package managers, since it is not tied directly.

This corresponds to the issue in the CLI.

**Comment by zewa666** [comment]
Great, installing through JSPM would also be a better alternative to the current Github download approach.

With regards to cli what would you say if we expand that to an object which might contain the commands?

Like:

```
{
  "plugins": [
      {  
        "name": "i18next",
        "endpoint": "github",    // where to start looking?  github, npm, gist
        "location": "/zewa666/aurelia-i18next",   // where is it in the end point?
        "cli": {
          commands: {
            parse: 'NAME_OF_EXPORTED_METHOD_FROM_INDEX',
            nextCmd: '...'
          }
        }
      }
  ]
}
```

EDIT:
It would be also nice to include a property like `demo` with the path to a working example. Might be helpful for pages listing all plugins (like the FAQ)

**Comment by plwalters** [comment]
Forgot to close this out before.
